# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3588s-orangepi-5.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3588s-orangepi-5b.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3566-orangepi-cm4.dtb
#dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3588-rock-5b.dtb

subdir-y := $(dts-dirs) overlay
